version: "3.8"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

services:
  extracon:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    entrypoint: >
      /bin/sh -c "
        set -e
        python ./main.py
        /bin/bash || exit 0
      "
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging: *default-logging
    networks: [ "extracon" ]
    volumes:
      - ./files/beneficiario:/usr/src/code/files

networks:
  extracon:
